package edu.ubbcluj.backend.model;

import java.util.Date;

/**
 * Messages generated by hbm2java
 */
public class Messages implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Users receiverId;
	private Users senderId;
	private String body;
	private Date date;

	
	public Messages() {
	}

	public Messages(int id) {
		this.id = id;
	}

	public Messages(int id, Users usersByReceiverId, Users usersBySenderId,
			String body, Date date) {
		this.id = id;
		this.receiverId = usersByReceiverId;
		this.senderId = usersBySenderId;
		this.body = body;
		this.date = date;
	}
	
	public Messages(Users usersByReceiverId, Users usersBySenderId,
			String body, Date date) {
		this.receiverId = usersByReceiverId;
		this.senderId = usersBySenderId;
		this.body = body;
		this.date = date;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Users getUsersByReceiverId() {
		return this.receiverId;
	}

	public void setUsersByReceiverId(Users usersByReceiverId) {
		this.receiverId = usersByReceiverId;
	}

	public Users getUsersBySenderId() {
		return this.senderId;
	}

	public void setUsersBySenderId(Users usersBySenderId) {
		this.senderId = usersBySenderId;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
	
	public String toString() {
		return "Users [id=" + id + ", receiverId=" + receiverId.getId() + ", senderId=" + senderId.getId()
				+", body= "+ body + ", date=" + date+ "]";
	}

}
