package edu.ubbcluj.backend.model;
// Generated Feb 4, 2015 1:47:58 PM by Hibernate Tools 4.3.1

/**
 * Places generated by hbm2java
 */
public class Places implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private String type;
	private Float coordX;
	private Float coordY;

	public Places() {
	}

	public Places(int id) {
		this.id = id;
	}

	public Places(int id, String name, String type, Float coordX, Float coordY) {
		this.id = id;
		this.name = name;
		this.type = type;
		this.coordX = coordX;
		this.coordY = coordY;
	}
	
	public Places( String name, String type, Float coordX, Float coordY) {
		this.name = name;
		this.type = type;
		this.coordX = coordX;
		this.coordY = coordY;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Float getCoordX() {
		return this.coordX;
	}

	public void setCoordX(Float coordX) {
		this.coordX = coordX;
	}

	public Float getCoordY() {
		return this.coordY;
	}

	public void setCoordY(Float coordY) {
		this.coordY = coordY;
	}

	@Override
	public String toString() {
		return "Places [id=" + id + ", name=" + name + ", type=" + type
				+ ", coordX=" + coordX + ", coordY=" + coordY + "]";
	}

}
