package edu.ubbcluj.backend.model;
// Generated Feb 4, 2015 1:47:58 PM by Hibernate Tools 4.3.1

/**
 * Rating generated by hbm2java
 */
public class Rating implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Services services;
	private Users users;
	private Integer rate;

	public Rating() {
	}

	public Rating(int id) {
		this.id = id;
	}

	public Rating(int id, Services services, Users users, Integer rate) {
		this.id = id;
		this.services = services;
		this.users = users;
		this.rate = rate;
	}
	
	public Rating( Services services, Users users, Integer rate) {
		this.services = services;
		this.users = users;
		this.rate = rate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Integer getRate() {
		return this.rate;
	}

	public void setRate(Integer rate) {
		this.rate = rate;
	}
	
	public String toString(){
		
		return "Ratings [id=" + id + ", services=" + this.services.getId() + ", userid=" + this.users.getId()
				+ ", rate=" +this.rate+ "]";
	}

}
