package edu.ubbcluj.backend.model;


// Generated Feb 4, 2015 1:47:58 PM by Hibernate Tools 4.3.1

/**
 * Services generated by hbm2java
 */
public class Services implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String telephone;
	private String adress;
	private Float coordX;
	private Float coordY;


	public Services() {
	}
	
	public Services(Integer id) {
		this.id = id;
	}

	public Services(String name, String telephone, String adress, Float coordX,
			Float coordY) {
		this.name = name;
		this.telephone = telephone;
		this.adress = adress;
		this.coordX = coordX;
		this.coordY = coordY;
	}
	
	public Services(Integer id, String name, String telephone, String adress, Float coordX,
			Float coordY) {
		this.id = id;
		this.name = name;
		this.telephone = telephone;
		this.adress = adress;
		this.coordX = coordX;
		this.coordY = coordY;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getAdress() {
		return this.adress;
	}

	public void setAdress(String adress) {
		this.adress = adress;
	}

	public Float getCoordX() {
		return this.coordX;
	}

	public void setCoordX(Float coordX) {
		this.coordX = coordX;
	}

	public Float getCoordY() {
		return this.coordY;
	}

	public void setCoordY(Float coordY) {
		this.coordY = coordY;
	}
	
	public String toString() {
		return "Services [id=" + id + ", name=" + name + ", telephone=" + telephone
				+", adress= "+ adress + ", coordX=" + coordX + ", coordY=" + 
				coordY +  "]";
	}
	
	

}
