package edu.ubbcluj.backend.model;


// Generated Feb 4, 2015 1:47:58 PM by Hibernate Tools 4.3.1

/**
 * Servicetype generated by hbm2java
 */
public class Servicetype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Services services;
	private Type type;
	

	public Servicetype() {
	}

	public Servicetype(int id) {
		this.id = id;
	}

	public Servicetype(int id, Services services, Type type) {
		this.id = id;
		this.services = services;
		this.type = type;
	}
	
	public Servicetype( Services services, Type type) {
		this.services = services;
		this.type = type;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}
	
	public String toString() {
		return "Service-Type["+"serviceid: "+this.services.getId()+" typeid: "+this.type.getTypeId()+"]";
	}
	


}
