package edu.ubbcluj.backend.model;


// Generated Feb 4, 2015 1:47:58 PM by Hibernate Tools 4.3.1



/**
 * Type generated by hbm2java
 */
public class Type implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int typeId;
	private String name;

	public Type() {
	}

	public Type(int typeId) {
		this.typeId = typeId;
	}

	public Type(int typeId, String name) {
		this.typeId = typeId;
		this.name = name;
		
	}
	
	public Type( String name) {
		this.name = name;
		
	}

	public int getTypeId() {
		return this.typeId;
	}

	public void setTypeId(int typeId) {
		this.typeId = typeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Override
	public String toString() {
		return "Type [id=" + typeId + ", name=" + name  + "]";
	}

	
	

}
