package edu.ubbcluj.backend.model;
// Generated Feb 4, 2015 1:47:58 PM by Hibernate Tools 4.3.1

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String usertype;
	private String username;
	private String password;
	private String firstname;
	private String lastname;
	private String email;
	

	public Users() {
	}

	public Users(int id) {
		this.id = id;
	}

	public Users(int id, String usertype, String username, String password,
			String firstname, String lastname, String email) {
		this.id = id;
		this.usertype = usertype;
		this.username = username;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
	}
	
	public Users( String usertype, String username, String password,
			String firstname, String lastname, String email) {
		this.usertype = usertype;
		this.username = username;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUsertype() {
		return this.usertype;
	}

	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	public String toString() {
		return "Users [id=" + id + ", usertype=" + usertype + ", username=" + username
				+", password= "+ password + ", firtname=" + firstname + ", lastname=" + 
				lastname + ", email"+ email + "]";
	}

}
